/**
 * Contains all languages that are no programming lanuages
 * @author Fabian Beuke <mail@beuke.org>
 * @license AGPL-3.0
 * @see {@link https://github.com/github/linguist/blob/master/lib/linguist/languages.yml}
 */
export default [
    "Adblock Filter List",
    "ApacheConf",
    "ApacheConf",
    "Arduino",
    "Batchfile",
    "BitBake",
    "CMAKE",
    "CMake",
    "CSS",
    "Dockerfile",
    "GCC Machine Description",
    "Gettext Catalog",
    "Gherkin",
    "Groff",
    "HCL",
    "HTML",
    "Handlebars",
    "Jinja",
    "JSON",
    "Jsonnet",
    "Jupyter Notebook",
    "Lex",
    "M4",
    "Makefile",
    "Markdown",
    "NSIS",
    "Nginx",
    "Nunjucks",
    "PLSQL",
    "PLpgSQL",
    "Perl6",
    "Protocol Buffer",
    "QMake",
    "Roff",
    "SaltStack",
    "SCSS",
    "Starlark",
    "Stylus",
    "Scilab",
    "Smarty",
    "TeX",
    "Vue",
    "Vim script",
    "XML",
    "XSLT",
    "Yacc",
    "YAML"
]
